# Generated by Django 5.2.1 on 2025-09-16 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_alter_inventoryitem_gym'),
        ('multiple_gym', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcategory',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multiple_gym.gym'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='icon',
            field=models.ImageField(upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
