# Generated by Django 5.2.1 on 2025-09-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membertrainerassignment',
            unique_together=set(),
        ),
    ]
