# Generated by Django 5.2.1 on 2025-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_management', '0002_alter_membertrainerassignment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
    ]
