# Generated by Django 5.2.1 on 2025-09-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_management', '0003_alter_trainingsession_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipant',
            name='zoom_join_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='zoom_joined',
            field=models.BooleanField(default=False, help_text='Has joined the Zoom session'),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='zoom_leave_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='zoom_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='zoom_notified',
            field=models.BooleanField(default=False, help_text='Has been notified about Zoom session'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='is_zoom_session',
            field=models.BooleanField(default=False, help_text='Is this a Zoom session?'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='zoom_host_key',
            field=models.CharField(blank=True, help_text='Zoom Host Key', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, help_text='Zoom Meeting ID', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='zoom_meeting_password',
            field=models.CharField(blank=True, help_text='Zoom Meeting Password', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='zoom_meeting_url',
            field=models.URLField(blank=True, help_text='Zoom Meeting Join URL'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='zoom_recording_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic recording'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='zoom_session_start_time',
            field=models.DateTimeField(blank=True, help_text='When Zoom session was actually started', null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='zoom_session_started',
            field=models.BooleanField(default=False, help_text='Has Zoom session been started?'),
        ),
    ]
