# Generated by Django 5.2.1 on 2025-09-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('gymadmin', 'Gym Admin'), ('member', 'Member'), ('trainer', 'Trainer')], default='member', max_length=20),
        ),
    ]
